# Generated by Django 5.2 on 2025-04-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("SHG", "Self Help Group"), ("FPG", "Farmer Producer Group")],
                default="Self Help Group",
                max_length=3,
            ),
            preserve_default=False,
        ),
    ]
