# Generated by Django 5.1.5 on 2025-04-12 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_product_created_at_product_is_available_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="fpg",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fpg_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="shg",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shg_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
