# Generated by Django 5.1.5 on 2025-04-12 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_buyrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="fpg",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fpg_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_placed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
