# Generated by Django 5.1.5 on 2025-04-12 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_order_fpg_alter_order_buyer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="fpg",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fpg_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
