# Generated by Django 5.1.5 on 2025-04-13 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_order_fpg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="fpg",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fpg_orders",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
