# Generated by Django 5.1.5 on 2025-04-17 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_product_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
    ]
